# Generated by Django 4.2.11 on 2025-11-03 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messagebox_images/')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('paragraph_class', models.CharField(blank=True, default='default_paragraph_class', max_length=200)),
                ('text_Account_name', models.TextField(default='Default Account Name')),
                ('text_Transaction_Type', models.TextField(default='Default Transaction Type')),
                ('text_Transaction_Amount', models.TextField(default='Default Transaction Amount')),
                ('text_Transaction_Currency', models.TextField(default='Default Transaction Currency')),
                ('text_Account_Number', models.TextField(default='Default Account Number')),
                ('text_Transaction_Narration', models.TextField(default='Default Transaction Narration')),
                ('text_Transaction_Remarks', models.TextField(default='Default Transaction Remarks')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(default=datetime.datetime.now)),
                ('text_Available_Balance', models.TextField(default='Default Available Balance')),
                ('text_Cleared_Balance', models.TextField(default='Default Cleared Balance')),
                ('text_News_Update1', models.TextField(default='Default News Update1')),
                ('text_News_Update2', models.TextField(default='Default News Update2')),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message1', models.CharField(default='First Page Instruction', max_length=255)),
                ('message2', models.CharField(default='Bank number ', max_length=255)),
                ('message3', models.CharField(default='your Bank Name ', max_length=255)),
                ('message4', models.CharField(default='Note Instructions', max_length=255)),
                ('message5', models.CharField(default='Final Note Instructions', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateField()),
                ('bank_account_number', models.TextField()),
                ('first_message', models.TextField()),
                ('payment_method', models.TextField()),
                ('confirmation_code', models.TextField()),
                ('second_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('message1', models.TextField()),
                ('message2', models.TextField()),
                ('message3', models.TextField()),
                ('message4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='sent_emails/images/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transaction_images/')),
                ('month', models.DateField()),
                ('amount', models.TextField(default='Default Money Received')),
                ('Recipient_Name', models.TextField(default='Default Recipient Details')),
                ('Sender_Name', models.TextField(default='Default Sender Details')),
                ('Sender_Bank', models.TextField(default='Default Sender Details')),
                ('Sender_Account', models.TextField(default='Default Sender Details')),
                ('Transaction_Type', models.TextField(default='Default Transaction Type')),
                ('Transaction_Number', models.TextField(default='Default Transaction Number')),
                ('Credited_To', models.TextField(default='Default Credited To')),
                ('is_new_transaction', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=10)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
