# Generated by Django 4.2.11 on 2025-11-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='confirmation_code',
            new_name='Routing_number',
        ),
    ]
