# Generated by Django 4.2.11 on 2025-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0002_rename_confirmation_code_mymodel_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Bank_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Transaction_ID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='Routing_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='bank_account_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='first_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='second_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
