# Generated by Django 4.2.10 on 2024-03-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0008_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_class',
            field=models.CharField(blank=True, default='default_paragraph_class', max_length=200),
        ),
    ]
