# Generated by Django 4.2.10 on 2024-03-12 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0009_alter_paragraph_paragraph_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='text',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Account_Number',
            field=models.TextField(default='Default Account Number'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Account_name',
            field=models.TextField(default='Default Account Name'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Available_Balance',
            field=models.TextField(default='Default Available Balance'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Cleared_Balance',
            field=models.TextField(default='Default Cleared Balance'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_News_Update1',
            field=models.TextField(default='Default News Update1'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_News_Update2',
            field=models.TextField(default='Default News Update2'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Transaction_Amount',
            field=models.TextField(default='Default Transaction Amount'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Transaction_Currency',
            field=models.TextField(default='Default Transaction Currency'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Transaction_Narration',
            field=models.TextField(default='Default Transaction Narration'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Transaction_Remarks',
            field=models.TextField(default='Default Transaction Remarks'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text_Transaction_Type',
            field=models.TextField(default='Default Transaction Type'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
