# Generated by Django 4.2.10 on 2024-03-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0010_remove_paragraph_text_paragraph_text_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
