# Generated by Django 4.2.10 on 2024-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0012_alter_paragraph_text_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='text_Account_name',
            field=models.TextField(default='Default Account Name'),
        ),
    ]
