# Generated by Django 4.2.10 on 2024-03-12 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0013_alter_paragraph_text_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebox',
            name='paragraph_class',
            field=models.CharField(blank=True, default='default_paragraph_class', max_length=200),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Account_Number',
            field=models.TextField(default='Default Account Number'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Account_name',
            field=models.TextField(default='Default Account Name'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Available_Balance',
            field=models.TextField(default='Default Available Balance'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Cleared_Balance',
            field=models.TextField(default='Default Cleared Balance'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_News_Update1',
            field=models.TextField(default='Default News Update1'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_News_Update2',
            field=models.TextField(default='Default News Update2'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Transaction_Amount',
            field=models.TextField(default='Default Transaction Amount'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Transaction_Currency',
            field=models.TextField(default='Default Transaction Currency'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Transaction_Narration',
            field=models.TextField(default='Default Transaction Narration'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Transaction_Remarks',
            field=models.TextField(default='Default Transaction Remarks'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='text_Transaction_Type',
            field=models.TextField(default='Default Transaction Type'),
        ),
        migrations.AlterField(
            model_name='messagebox',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='messagebox',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
