# Generated by Django 4.2.10 on 2024-03-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0014_messagebox_paragraph_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('image', models.ImageField(upload_to='transaction_images/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=1)),
            ],
        ),
    ]
