# Generated by Django 4.2.10 on 2024-03-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0017_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
    ]
