# Generated by Django 4.2.10 on 2024-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0032_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Recipient_Details',
            new_name='Recipient_Name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Sender_Details',
            new_name='Sender_Account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Payment_Method',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Sender_Bank',
            field=models.TextField(default='Default Sender Details'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Sender_Name',
            field=models.TextField(default='Default Sender Details'),
        ),
    ]
