# Generated by Django 4.2.10 on 2024-03-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0033_rename_recipient_details_transaction_recipient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_read',
            new_name='is_new_transaction',
        ),
    ]
