# Generated by Django 4.2.10 on 2024-03-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0034_rename_is_read_transaction_is_new_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_new_transaction', models.BooleanField(default=False)),
            ],
        ),
    ]
