# Generated by Django 4.2.10 on 2024-03-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0035_notificationstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationStatus',
        ),
    ]
