# Generated by Django 4.2.10 on 2024-03-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0039_sentemail_alter_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
