# Generated by Django 4.2.10 on 2024-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0040_sentemail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
