# Generated by Django 4.2.10 on 2024-03-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0041_sentemail_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemail',
            name='edited_at',
        ),
    ]
