# Generated by Django 4.2.10 on 2024-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0042_remove_sentemail_edited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('bank_account_name', models.TextField()),
                ('first_message', models.TextField()),
                ('payment_method', models.TextField()),
                ('confirmation_code', models.TextField()),
                ('second_message', models.TextField()),
            ],
        ),
    ]
