# Generated by Django 4.2.10 on 2024-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0044_rename_bank_account_name_mymodel_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
