# Generated by Django 4.2.10 on 2024-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0045_alter_mymodel_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message1', models.TextField()),
                ('message2', models.TextField()),
                ('message3', models.TextField()),
                ('message4', models.TextField()),
            ],
        ),
    ]
