# Generated by Django 4.2.10 on 2024-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0046_mytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
