# Generated by Django 4.2.10 on 2024-04-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0047_alter_mytransfer_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message1', models.CharField(max_length=255)),
                ('message2', models.CharField(max_length=255)),
                ('message3', models.CharField(max_length=255)),
                ('message4', models.CharField(max_length=255)),
            ],
        ),
    ]
