# Generated by Django 4.2.10 on 2024-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0048_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message1',
            field=models.CharField(default='First Page Instruction', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message2',
            field=models.CharField(default='Bank number ', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message3',
            field=models.CharField(default='your Bank Name ', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='message4',
            field=models.CharField(default='Note Instructions', max_length=255),
        ),
    ]
