# Generated by Django 4.2.10 on 2024-04-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0049_alter_messagemodel_message1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='message5',
            field=models.CharField(default='Note Instructions', max_length=255),
        ),
    ]
