# Generated by Django 4.2.10 on 2024-04-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0050_messagemodel_message5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='message5',
            field=models.CharField(default='Final Note Instructions', max_length=255),
        ),
    ]
