# Generated by Django 4.2.11 on 2025-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0051_alter_messagemodel_message5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
