# Generated by Django 4.2.11 on 2025-01-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyhouse', '0052_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount1',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
